### ISSUE TITLE
Docs not generated

### ISSUE THREAD

**Issue by RobCranfill** [adafruit/Adafruit_CircuitPython_USB_Host_MIDI#6]
The 'Read the Docs' link mentioned in the ReadMe page

[https://docs.circuitpython.org/projects/usb-host-midi/en/latest/](https://docs.circuitpython.org/projects/usb-host-midi/en/latest/)

gets a 404 error.

**Comment by tannewt** [comment]
I've set it up. Thanks for the issue.
